// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class HoldLogRawMaterialDto : BaseModel
    {
        public long? HoldLogId { get; set; }
        public long? MaterialLotId { get; set; }
        public string MaterialLotCode { get; set; }
        public string LotNo { get; set; }
        public string Reason { get; set; }
        public Boolean? IsPicture { get; set; }
        public string FileName { get; set; }
        public string HoldStatus { get; set; }
        public IFormFile? file { get; set; }
        public string HoldStatusName { get; set; }
        public List<long>? ListId { get; set; }



        public long? QCIQCMasterId { get; set; }
        public long? StaffId { get; set; }
        public string StaffName { get; set; } = string.Empty;
        public int? CheckResult { get; set; }
        public DateTime? CheckDate { get; set; }

    }

}
