// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class HoldLogFGDto : BaseModel
    {
        public long? HoldLogId { get; set; }
        public long? FGInventoryId { get; set; }
        public string BuyerQR { get; set; }
        public string SemiLotCode { get; set; }
        public string LotNo { get; set; }
        public string Reason { get; set; }
        public Boolean? IsPicture { get; set; }
        public string FileName { get; set; }
        public string HoldStatus { get; set; }
        public IFormFile? file { get; set; }
        public string HoldStatusName { get; set; }
        public string FQCSOName { get; set; } = string.Empty;
        public string BoxQR { get; set; } = string.Empty;
        public List<long>? ListId { get; set; }
    }

}
