// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD.Models
{
    public partial class Bin
    {
        [Key]
        public long BinId { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string BinCode { get; set; }
        public long ShelfId { get; set; }
        public byte BinLevel { get; set; }
        public byte? BinIndex { get; set; }
        public byte? BinStatus { get; set; }
        [StringLength(12)]
        [Unicode(false)]
        public string ESLCode { get; set; }
        [Required]
        public bool? isActived { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("ShelfId")]
        [InverseProperty("Bin")]
        public virtual Shelf Shelf { get; set; }
    }
}