// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD.Models
{
    public partial class FGSOMaster
    {
        public FGSOMaster()
        {
            FGSODetail = new HashSet<FGSODetail>();
        }

        [Key]
        public long FGsoId { get; set; }
        public bool? FGsoStatus { get; set; }
        [StringLength(50)]
        public string Requester { get; set; }
        [Precision(0)]
        public DateTime? DueDate { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [InverseProperty("FGso")]
        public virtual ICollection<FGSODetail> FGSODetail { get; set; }
    }
}