// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD.Models
{
    public partial class FGSODetail
    {
        public FGSODetail()
        {
            FGSOPicked = new HashSet<FGSOPicked>();
        }

        [Key]
        public long FGsoDetailId { get; set; }
        public long FGsoId { get; set; }
        public long MaterialId { get; set; }
        public long? LotId { get; set; }
        public long? PickingLotId { get; set; }
        [Column(TypeName = "decimal(10, 3)")]
        public decimal? FGsoOrderQty { get; set; }
        public bool? FGsoDetailStatus { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(0)]
        public DateTime? PickingDate { get; set; }
        public long? PickingUserId { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("FGsoId")]
        [InverseProperty("FGSODetail")]
        public virtual FGSOMaster FGso { get; set; }
        [InverseProperty("FGsoDetail")]
        public virtual ICollection<FGSOPicked> FGSOPicked { get; set; }
    }
}