// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD.Models
{
    [Index("LineName", Name = "UC_Line_LineName", IsUnique = true)]
    public partial class Line
    {
        [Key]
        public long LineId { get; set; }
        [StringLength(50)]
        public string LineName { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        [StringLength(18)]
        [Unicode(false)]
        public string HMIMacAddress { get; set; }
        public bool? IsUsed { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }
    }
}