// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD.Models
{
    public partial class Lot
    {
        public Lot()
        {
            LotNG = new HashSet<LotNG>();
        }

        [Key]
        public long Id { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string LotSerial { get; set; }
        public long? WoId { get; set; }
        public long MaterialId { get; set; }
        public bool LotStatus { get; set; }
        [Column(TypeName = "decimal(10, 3)")]
        public decimal? Qty { get; set; }
        [Precision(0)]
        public DateTime? QCDate { get; set; }
        public bool? QCResult { get; set; }
        [Precision(0)]
        public DateTime? IncomingDate { get; set; }
        public long? WarehouseType { get; set; }
        public long? TrayId { get; set; }
        public long? BinId { get; set; }
        [Column(TypeName = "decimal(10, 3)")]
        public decimal? TotalSOQty { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("MaterialId")]
        [InverseProperty("Lot")]
        public virtual Material Material { get; set; }
        [InverseProperty("Lot")]
        public virtual ICollection<LotNG> LotNG { get; set; }
    }
}