// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD.Models
{
    public partial class Material
    {
        public Material()
        {
            DeliveryOrder = new HashSet<DeliveryOrder>();
            ForecastPO = new HashSet<ForecastPO>();
            Lot = new HashSet<Lot>();
            MaterialSODetail = new HashSet<MaterialSODetail>();
            Material_Buyer = new HashSet<Material_Buyer>();
            Material_Supplier = new HashSet<Material_Supplier>();
            WorkOrder = new HashSet<WorkOrder>();
        }

        [Key]
        public long MaterialId { get; set; }
        [Required]
        [StringLength(11)]
        [Unicode(false)]
        public string MaterialCode { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        public long MaterialType { get; set; }
        public long? ProductType { get; set; }
        public long? Model { get; set; }
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? Inch { get; set; }
        public long Unit { get; set; }
        public long? QCMasterId { get; set; }
        [Column(TypeName = "decimal(10, 3)")]
        public decimal? StockQty { get; set; }
        public long? SupplierId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Grade { get; set; }
        [StringLength(12)]
        [Unicode(false)]
        public string Color { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ResinType { get; set; }
        [StringLength(12)]
        [Unicode(false)]
        public string FlameClass { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }
        [StringLength(11)]
        [Unicode(false)]
        public string MoldCode { get; set; }

        [ForeignKey("MaterialType")]
        [InverseProperty("MaterialMaterialTypeNavigation")]
        public virtual sysTbl_CommonDetail MaterialTypeNavigation { get; set; }
        [ForeignKey("Unit")]
        [InverseProperty("MaterialUnitNavigation")]
        public virtual sysTbl_CommonDetail UnitNavigation { get; set; }
        [InverseProperty("Material")]
        public virtual ICollection<DeliveryOrder> DeliveryOrder { get; set; }
        [InverseProperty("Material")]
        public virtual ICollection<ForecastPO> ForecastPO { get; set; }
        [InverseProperty("Material")]
        public virtual ICollection<Lot> Lot { get; set; }
        [InverseProperty("Material")]
        public virtual ICollection<MaterialSODetail> MaterialSODetail { get; set; }
        [InverseProperty("Material")]
        public virtual ICollection<Material_Buyer> Material_Buyer { get; set; }
        [InverseProperty("Material")]
        public virtual ICollection<Material_Supplier> Material_Supplier { get; set; }
        [InverseProperty("Material")]
        public virtual ICollection<WorkOrder> WorkOrder { get; set; }
    }
}