// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD.Models
{
    public partial class MaterialSODetail
    {
        public MaterialSODetail()
        {
            MaterialSOPicked = new HashSet<MaterialSOPicked>();
        }

        [Key]
        public long MsoDetailId { get; set; }
        public long MsoId { get; set; }
        public long MaterialId { get; set; }
        public long? LotId { get; set; }
        public long? PickingLotId { get; set; }
        [Column(TypeName = "decimal(10, 3)")]
        public decimal? SOrderQty { get; set; }
        public bool? MsoDetailStatus { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(0)]
        public DateTime? PickingDate { get; set; }
        public long? PickingUserId { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("MaterialId")]
        [InverseProperty("MaterialSODetail")]
        public virtual Material Material { get; set; }
        [ForeignKey("MsoId")]
        [InverseProperty("MaterialSODetail")]
        public virtual MaterialSOMaster Mso { get; set; }
        [InverseProperty("MsoDetail")]
        public virtual ICollection<MaterialSOPicked> MaterialSOPicked { get; set; }
    }
}