// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD.Models
{
    public partial class MaterialSOMaster
    {
        public MaterialSOMaster()
        {
            MaterialSODetail = new HashSet<MaterialSODetail>();
        }

        [Key]
        public long MsoId { get; set; }
        [Required]
        [StringLength(12)]
        [Unicode(false)]
        public string MsoCode { get; set; }
        public bool? MsoStatus { get; set; }
        [StringLength(50)]
        public string Requester { get; set; }
        [Precision(0)]
        public DateTime? DueDate { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [InverseProperty("Mso")]
        public virtual ICollection<MaterialSODetail> MaterialSODetail { get; set; }
    }
}