// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD.Models
{
    public partial class sysTbl_ExpoToken
    {
        [Key]
        [StringLength(200)]
        [Unicode(false)]
        public string ExpoToken { get; set; }
        [Required]
        public bool? isActived { get; set; }
    }
}