// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD.Models
{
    [Index("WO", Name = "UC_WO_WOCode", IsUnique = true)]
    public partial class WO
    {

        [Key]
        public long WOId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string WOCode { get; set; }
        public string ProductCode { get; set; }
        public long? ProductId { get; set; }
        public long BomId { get; set; }
        public int Target { get; set; }
        [Precision(0)]
        public DateTime? ManufacturingDate { get; set; }
        public string? Description { get; set; }
        public bool? isFinish { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }
    }
}