// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ESD.Models
{
    [Index("WoCode", Name = "UC_WorkOrder_WoCode", IsUnique = true)]
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            HMICounting = new HashSet<HMICounting>();
        }

        [Key]
        public long WoId { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string WoCode { get; set; }
        public bool? WOProcess { get; set; }
        public bool? IsChecked { get; set; }
        public bool? IsInputScan { get; set; }
        public long? FPOId { get; set; }
        public long MaterialId { get; set; }
        public long BomId { get; set; }
        public long? MoldId { get; set; }
        public long? LineId { get; set; }
        public int OrderQty { get; set; }
        [Precision(0)]
        public DateTime? StartDate { get; set; }
        public long? HMICountingId { get; set; }
        public int? HMIQty { get; set; }
        public long? HMIStatus { get; set; }
        public int? ActualQty { get; set; }
        public int? NGQty { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("BomId")]
        [InverseProperty("WorkOrder")]
        public virtual Bom Bom { get; set; }
        [ForeignKey("MaterialId")]
        [InverseProperty("WorkOrder")]
        public virtual Material Material { get; set; }
        [InverseProperty("Wo")]
        public virtual ICollection<HMICounting> HMICounting { get; set; }
    }
}