// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class BomDto : BaseModel
    {
        public long? BomId { get; set; }
        public long? BuyerId { get; set; }
        public string BuyerCode { get; set; }
        public string BomVersion { get; set; }
        public string Ver { get; set; }
        public long? ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public long? ModelId { get; set; }
        public string ModelCode { get; set; }
        public DateTime? DateApply { get; set; }
        public string Description { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string ProcessCode { get; set; }

        public int Step { get; set; }
        public string BomProcessCode { get; set; }
    }

    public partial class BomProcessDto : BaseModel
    {
        public string ProductCode { get; set; }
        public string BuyerCode { get; set; }
        public string BomVersion { get; set; }
        public string Ver { get; set; }
        public long? BomProcessId { get; set; }
        public DateTime? DateApply { get; set; }
        public long? BomId { get; set; }
        public string CHA { get; set; }
        public int Step { get; set; }
        public string ProcessCode { get; set; }
        public string BomProcessCode { get; set; }
        public string ProcessName { get; set; }
    }

    public partial class BomProcessMaterialDto : BaseModel
    {
        public long? ProcessMaterialId { get; set; }
        public long? BomProcessId { get; set; }
        public long? MaterialId { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public decimal? CuttingSize { get; set; }
        public string BomProcessType { get; set; }
        public string MaterialUnit { get; set; }
        public decimal? Pitch { get; set; }
        public int? Cavity { get; set; }
        public int? RollUse { get; set; }
        public string? Note { get; set; }
        public long? WOId { get; set; }
        public long? WOProcessId { get; set; }


        public string ProductCode { get; set; }
        public string BuyerCode { get; set; }
        public string BomVersion { get; set; }
        public string Ver { get; set; }
        public DateTime? DateApply { get; set; }
        public long? BomId { get; set; }
        public string CHA { get; set; }
        public int Step { get; set; }
        public string ProcessCode { get; set; }
        public string BomProcessCode { get; set; }
        public string ProcessName { get; set; }
    }

    public partial class BomProcessMaterialExcelDto
    {
        public long? BomProcessId { get; set; }
        public string MaterialCode { get; set; }
        public string Cavity { get; set; }
        public string BomProcessType { get; set; }
        public string Pitch { get; set; }
        public string CuttingSize { get; set; }
        public string RollUse { get; set; }
        public string Note { get; set; }
    }
}