// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class MaterialDto : BaseModel
    {
        public long? MaterialId { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string MaterialTypeId { get; set; }
        public string MaterialTypeName { get; set; }
        public string MaterialUnit { get; set; }
        public int? Width { get; set; }
        public int? Length { get; set; }
        public int? StockQty { get; set; }
        public string Description { get; set; }
        public long? IQCMaterialId { get; set; }
        public long? IQCRawMaterialId { get; set; }
        public string? IQCMaterialName { get; set; }
        public string? IQCRawMaterialName { get; set; }
        public long? SupplierId { get; set; }
        public string SupplierCode { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int? ExpirationMonth { get; set; }

        //klq
        public DateTime? ReceivedDate { get; set; }
        public string MaterialLotCode { get; set; } = string.Empty;
        public string LotNo { get; set; } = string.Empty;
        public bool? Expiration { get; set; }
        public decimal? TotalStock { get; set; }
    }

    public partial class MaterialExcelDto
    {
        public string MaterialCode { get; set; }
        public string Description { get; set; }
        public string MaterialTypeCode { get; set; }
        public string UnitCode { get; set; }
        public string QCMasterCode { get; set; }
        public string SupplierCode { get; set; }
        public string Grade { get; set; }
        public string Color { get; set; }
        public string ResinType { get; set; }
        public string FlameClass { get; set; }
    }
}
