// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class RoutingDto : BaseModel
    {
        public long? RoutingId { get; set; }
        public string ModelCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string BomVer { get; set; }
        public string ProcessCode { get; set; }
        public string ProcessName { get; set; }
        public bool? IsFinalProcess { get; set; }
        
    }
}
