// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class HistoryStatusDto : BaseModel
    {
        public int? MaterialLotId { get; set; }
        public long? MaterialLotCode { get; set; }
        public int? Length { get; set; }
        public int? Width { get; set; }
        public int? LotStatus { get; set; }
        public string LotStatusName { get; set; } = string.Empty;
        public string LocationName { get; set; } = string.Empty;
        public string Result { get; set; } = string.Empty;
        public string WOCode { get; set; } = string.Empty;
        public string ProcessCode { get; set; } = string.Empty;
        public int? ProcessLevel { get; set; }
        public string FactoryName { get; set; } = string.Empty;
        public string SemiLotCode { get; set; } = string.Empty;
        public string ProductCode { get; set; } = string.Empty;
        public string CreateDateMapping { get; set; } = string.Empty;
        public string AreaCode { get; set; } = string.Empty;

    }
}