// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class HistoryLotTrackingSlitDto : BaseModel
    {
        public long? SlitOrderId { get; set; }
        public string? MaterialLotCode { get; set; }
        public string? Description { get; set; }
        public string? OrderDate { get; set; }
        public string? StaffNameSlit { get; set; }
        public string? LineName { get; set; }
        public DateTime? createdDate { get; set; }
     
      
    }
}