// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class HistoryLotTrackingDto : BaseModel
    {
        public int? id { get; set; }
        public long? WOSemiLotAPPId { get; set; }
        public string? BuyerQR { get; set; }
        public string? SemiLotCode { get; set; }
        public int? OriginQty { get; set; }
        public int? ActualQty { get; set; }
        public string? StaffName { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int? ProcessLevel { get; set; }
        public string? ProcessName { get; set; }
        public string? ProcessCode { get; set; }
        public string? locationName { get; set; }
        public string? MoldName { get; set; }
        public string? WOCode { get; set; }
    }
}