// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class HistoryLotTrackingDetailDto : BaseModel
    {
        public int? id { get; set; }
        public string? MaterialLotCode { get; set; }
        public string? SemiLotCode { get; set; }
        public int? OKQty { get; set; }
        public string? StaffName { get; set; }
        public string? Description { get; set; }
        public string? LotNo { get; set; }
        public string? SlitOrCut { get; set; }
        public string? FactoryName { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? ReceivedDate { get; set; }
        public DateTime? ExportDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
      
    }
}