// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class QCAPPMasterDto : BaseModel
    {
        public long? QCAPPMasterId { get; set; }
        public string QCAPPMasterName { get; set; }
        public string Explain { get; set; }
        public List<ProductDto> Products { get; set; } = default;
        public string ProductList { get; set; }
        public Boolean? IsConfirm { get; set; }
        public long? ProductId { get; set; }
    }

    public partial class QCAPPDetailDto : BaseModel
    {
        public string SemiLotCode { get; set; } = string.Empty;
        public string MaterialLotCode { get; set; } = string.Empty;
        public long QCAPPDetailId { get; set; }
        public long QCFQCDetailId { get; set; }
        public long? QCAPPMasterId { get; set; }
        public long? QCFQCMasterId { get; set; }
        public long? QCTypeId { get; set; }
        public long? QCItemId { get; set; }
        public long? QCStandardId { get; set; }
        public string? QCTypeName { get; set; }
        public string? QCItemName { get; set; }
        public string? QCStandardName { get; set; }
        public int TextValue { get; set; }
    }
}
