// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class QCOQCMasterDto : BaseModel
    {
        public long? QCOQCMasterId { get; set; }
        public string QCOQCMasterName { get; set; }
        public long? OQCType { get; set; }
        public string OQCTypeName { get; set; }
        public string Explain { get; set; }
        public List<ProductDto> Products { get; set; } = default;
        public string ProductList { get; set; }
        public Boolean? IsConfirm { get; set; }
        public long? ProductId { get; set; }
    }

    public partial class QCOQCDetailDto : BaseModel
    {
        public long QCOQCDetailId { get; set; }
        public long? QCOQCMasterId { get; set; }
        public long? QCTypeId { get; set; }
        public long? QCItemId { get; set; }
        public long? QCStandardId { get; set; }
        public long? QCToolId { get; set; }
        public long? QCFrequencyId { get; set; }

        public string? QCTypeName { get; set; }
        public string? QCItemName { get; set; }
        public string? QCStandardName { get; set; }
        public string? QCToolName { get; set; }
        public string? QCFrequencyName { get; set; }
        public string? TextValue { get; set; }
    }
}
