// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>;
using ESD.Models.Dtos.Common;

namespace ESD.Models.Dtos
{
    public partial class QCPQCMasterDto : BaseModel
    {
        public long? QCPQCMasterId { get; set; }
        public string QCPQCMasterName { get; set; }
        public DateTime REVDate { get; set; }
        public string Description { get; set; }
        public string ImageFile { get; set; }
        public long? ProductId { get; set; }
        //public string ProductCode { get; set; }
        public string Explain { get; set; }
        public List<long> Products { get; set; } = default;
        public List<string> Process { get; set; } = default;
        public string ProductList { get; set; }
        public string ProcessList { get; set; }
        public Boolean? IsConfirm { get; set; }
        public IFormFile? file { get; set; }
        public long? ProcessId { get; set; }
        public string ProcessCode { get; set; }
    }

    public partial class QCPQCDetailSLDto : BaseModel
    {
        public long QCPQCDetailSLId { get; set; }
        public long? QCPQCMasterId { get; set; }
        public long? QCTypeId { get; set; }
        public long? QCItemId { get; set; }
        public long? QCStandardId { get; set; }
        public long? QCToolId { get; set; }
        public long? QCFrequencyId { get; set; }

        public string? QCTypeName { get; set; }
        public string? QCItemName { get; set; }
        public string? QCStandardName { get; set; }
        public string? QCToolName { get; set; }
        public string? QCFrequencyName { get; set; }

        public string LocationToCheck { get; set; }
        public string ImageFile { get; set; }
        public IFormFile? file { get; set; }
    }

    public partial class QCPQCDetailASDto : BaseModel
    {
        public long QCPQCDetailASId { get; set; }
        public long? QCPQCMasterId { get; set; }
        public long? QCTypeId { get; set; }
        public long? QCItemId { get; set; }
        public long? QCStandardId { get; set; }
        public long? QCToolId { get; set; }
        public long? QCFrequencyId { get; set; }

        public string? QCTypeName { get; set; }
        public string? QCItemName { get; set; }
        public string? QCStandardName { get; set; }
        public string? QCToolName { get; set; }
        public string? QCFrequencyName { get; set; }

        public int Samples { get; set; }
        public int CHA_From { get; set; }
        public int CHA_To { get; set; }
        public long? WOProcessId { get; set; }
        public List<WOProcessDetailASDto?> ValueCheck { get; set; }
    }

    public partial class WOProcessDetailASDto : BaseModel
    {
        public long? WOProcessId { get; set; }
        public long? QCPQCDetailASId { get; set; }
        public int SampleNumber { get; set; }
        public string TextValue { get; set; }
    }
}
